APP_PORT: 8080

DB_NAME: "icp_messenger_dev"
DB_HOST: "localhost"
DB_USER: "postgres"
DB_PASSWORD: ""
DB_POOL_SIZE: 2
DB_PORT: 5432
DB_READ_TIMEOUT_MS: 100
DB_WRITE_TIMEOUT_MS: 500
DB_QUERY_TIMEOUT_MS: 500
DB_CONNECTION_MAX_LIFETIME_MINUTE: 30


SERVER_HTTP_READ_TIMEOUT_MS: 2000
SERVER_HTTP_WRITE_TIMEOUT_MS: 2000

HYSTRIX_STREAM_ADDRESS: ":8081"